/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Inventario;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import local.DAO.Autos_DAO;
import local.DAO.ExistenciaAutos_DAO;
import local.DAO.Proveedores_DAO;
import local.DAO.Roles_DAO;
import local.LC.AutosLC;
import local.LC.ProveedoresLC;
import local.PrincipalFrame.Principal_Frame;

/**
 *
 * @author Leonel
 */
public class Auto_Existencia extends javax.swing.JInternalFrame {

    //variables Globales
    DefaultTableModel modelAutoExistencia;
    ExistenciaAutos_DAO exDao = new ExistenciaAutos_DAO();
    Proveedores_DAO provDao = new Proveedores_DAO();
    Autos_DAO autDao = new Autos_DAO();
    int idExistencia = -1;
    
    public Auto_Existencia() {
        //Cargando los datos de la tabla
        modelAutoExistencia = new DefaultTableModel(null, getColums());
        getRows();

        //Iniciando los componentes del formulario
        initComponents();
        setVisible(true);
        
        //Acciones por rol
        accionRol();

        //Carrgado datos
        autDao.listaAutos(jcbxAuto);
        provDao.listaProveedor(jcbxProveedor);

        //Ocultar columnas
        jtblAutoExistencia.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblAutoExistencia.getColumnModel().getColumn(0).setMinWidth(0);
        jtblAutoExistencia.getColumnModel().getColumn(0).setPreferredWidth(0);

        //Centrando el formulario
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }
    
    private String[] getColums() {
        String[] columnas = new String[]{"Id", "Auto", "Proveedor", "Precio Compra", "Precio Venta", "Agregado por"};
        return columnas;
    }

    private void getRows() {
        ResultSet rs = exDao.getListExisAuto();

        try {
            Object datos[] = new Object[6];

            while (rs.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = rs.getObject(i + 1);
                }
                modelAutoExistencia.addRow(datos);
            }

            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos.");
            Logger.getLogger(Auto_Existencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void sDecimal(JTextField t){
        t.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != '.')){
                    getToolkit().beep();
                    e.consume();
                }
                if(c == '.' && t.getText().contains(".")){
                    e.consume();
                }
            }
        });
    }
    
    private void Limpiar() {
        jcbxAuto.setSelectedIndex(0);
        jcbxProveedor.setSelectedIndex(0);
        jtfCompra.setText("");
        jtfVenta.setText("");
        
        for (int i = 0; i < jtblAutoExistencia.getRowCount(); i++) {
            modelAutoExistencia.removeRow(i);
            i -= 1;
        }
    }
    
    //metodo para verificar los permisos para el formulario cargos
    private void accionRol(){
        Roles_DAO rolDao = new Roles_DAO();
        ResultSet rs = rolDao.listaTareas();
        int acciones;
        
        try {
            while(rs.next()){
                acciones = rs.getInt(1);
                switch(acciones){
                    case 19:
                        jrbtnAdd.setEnabled(true);
                        break;
                        
                    case 20:
                        jrbtnUpdate.setEnabled(true);
                        break;
                        
                    case 21:
                        jrbtnDelete.setEnabled(true);
                        break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Auto_Existencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtgAcciones = new javax.swing.ButtonGroup();
        jPanelAcciones = new javax.swing.JPanel();
        jrbtnAdd = new javax.swing.JRadioButton();
        jrbtnUpdate = new javax.swing.JRadioButton();
        jrbtnDelete = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAutoExistencia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbxAuto = new javax.swing.JComboBox<>();
        jcbxProveedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCompra = new javax.swing.JTextField();
        jtfVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Existencia Autos");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setRequestFocusEnabled(false);

        jPanelAcciones.setBackground(new java.awt.Color(80, 81, 79));

        jrbtnAdd.setBackground(new java.awt.Color(80, 81, 79));
        jbtgAcciones.add(jrbtnAdd);
        jrbtnAdd.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jrbtnAdd.setForeground(new java.awt.Color(242, 95, 92));
        jrbtnAdd.setText("Agregar");
        jrbtnAdd.setEnabled(false);

        jrbtnUpdate.setBackground(new java.awt.Color(80, 81, 79));
        jbtgAcciones.add(jrbtnUpdate);
        jrbtnUpdate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jrbtnUpdate.setForeground(new java.awt.Color(242, 95, 92));
        jrbtnUpdate.setText("Editar");
        jrbtnUpdate.setEnabled(false);

        jrbtnDelete.setBackground(new java.awt.Color(80, 81, 79));
        jbtgAcciones.add(jrbtnDelete);
        jrbtnDelete.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jrbtnDelete.setForeground(new java.awt.Color(242, 95, 92));
        jrbtnDelete.setText("Eliminar");
        jrbtnDelete.setEnabled(false);

        javax.swing.GroupLayout jPanelAccionesLayout = new javax.swing.GroupLayout(jPanelAcciones);
        jPanelAcciones.setLayout(jPanelAccionesLayout);
        jPanelAccionesLayout.setHorizontalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jrbtnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jrbtnDelete)
                .addContainerGap())
        );
        jPanelAccionesLayout.setVerticalGroup(
            jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnAdd)
                    .addComponent(jrbtnDelete)
                    .addComponent(jrbtnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblAutoExistencia.setModel(modelAutoExistencia);
        jtblAutoExistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblAutoExistenciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblAutoExistencia);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Automovil:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Proveedor:");

        jcbxAuto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jcbxProveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Precio Compra:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Precio Venta:");

        jtfCompra.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfVenta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfCompra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbxProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbxAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfVenta))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbxAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jcbxAuto.getSelectedIndex() >= 0 && jcbxProveedor.getSelectedIndex() >= 0 && !jtfCompra.getText().isEmpty() && !jtfVenta.getText().isEmpty()){
            if(jrbtnAdd.isSelected()){
                int i;
                ProveedoresLC pr = (ProveedoresLC) jcbxProveedor.getSelectedItem();
                AutosLC au = (AutosLC) jcbxAuto.getSelectedItem();
                int idau = au.getIdAuto(), idpr = pr.getIdProveedor();
                
                i = exDao.addExisAutos(idau, idpr, Double.parseDouble(jtfCompra.getText()), Double.parseDouble(jtfVenta.getText()));
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se logro completar la transaccion seleccionada");
                }
            } else if(jrbtnUpdate.isSelected()){
                int i;
                ProveedoresLC pr = (ProveedoresLC) jcbxProveedor.getSelectedItem();
                AutosLC au = (AutosLC) jcbxAuto.getSelectedItem();
                int idau = au.getIdAuto(), idpr = pr.getIdProveedor();
                
                i = exDao.updateExisAutos(idau, idpr, Double.parseDouble(jtfCompra.getText()), Double.parseDouble(jtfVenta.getText()), idExistencia);
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se logro completar la transaccion seleccionada");
                }
                idExistencia = -1;
            } else if(jrbtnDelete.isSelected()){
                int i;
                i = exDao.deleteExisAutos(idExistencia);
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se logro completar la transaccion seleccionada");
                }
                idExistencia = -1;
            } else{
                JOptionPane.showMessageDialog(null, "Debes de seleccionar una accion");
            }
            
            exDao.close();
        } else
            JOptionPane.showMessageDialog(null, "No debes dejar campos en blanco");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtblAutoExistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAutoExistenciaMouseClicked
        if(jrbtnDelete.isSelected() || jrbtnUpdate.isSelected()){
            idExistencia = (int) modelAutoExistencia.getValueAt(jtblAutoExistencia.getSelectedRow(), 0);
            String auto = (String) modelAutoExistencia.getValueAt(jtblAutoExistencia.getSelectedRow(), 1);
            String prov = (String) modelAutoExistencia.getValueAt(jtblAutoExistencia.getSelectedRow(), 2);
            BigDecimal com = (BigDecimal) modelAutoExistencia.getValueAt(jtblAutoExistencia.getSelectedRow(), 3);
            BigDecimal ven = (BigDecimal) modelAutoExistencia.getValueAt(jtblAutoExistencia.getSelectedRow(), 4);
            
            jtfCompra.setText(com.toString());
            jtfVenta.setText(ven.toString());
            
            for (int i = 0; i < jcbxAuto.getItemCount(); i++) {
                jcbxAuto.setSelectedIndex(i);
                
                if(jcbxAuto.getSelectedItem().toString().equals(auto)){
                    break;
                }
            }
            
            for (int i = 0; i < jcbxProveedor.getItemCount(); i++) {
                jcbxProveedor.setSelectedIndex(i);
                
                if(jcbxProveedor.getSelectedItem().toString().equals(prov)){
                    break;
                }
            }
        }
    }//GEN-LAST:event_jtblAutoExistenciaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAcciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jbtgAcciones;
    private javax.swing.JComboBox<String> jcbxAuto;
    private javax.swing.JComboBox<String> jcbxProveedor;
    private javax.swing.JRadioButton jrbtnAdd;
    private javax.swing.JRadioButton jrbtnDelete;
    private javax.swing.JRadioButton jrbtnUpdate;
    private javax.swing.JTable jtblAutoExistencia;
    private javax.swing.JTextField jtfCompra;
    private javax.swing.JTextField jtfVenta;
    // End of variables declaration//GEN-END:variables
}
