/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Inventario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import local.DAO.Marcas_DAO;
import local.DAO.Roles_DAO;
import local.PrincipalFrame.Principal_Frame;

/**
 *
 * @author Leonel
 */
public class Marcas extends javax.swing.JInternalFrame {

    //Variables Globales
    DefaultTableModel modeloMarcas;
    Marcas_DAO marDao = new Marcas_DAO();
    int idMarca = -1;
    
    public Marcas() {
        //Cargando los datos de la tabla
        modeloMarcas = new DefaultTableModel(null, getColums());
        getRows();

        //Iniciando los componentes del formulario
        initComponents();
        setVisible(true);

        //Acciones por rol
        accionRol();

        //Ocultar columnas
        jtblMarcas.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblMarcas.getColumnModel().getColumn(0).setMinWidth(0);
        jtblMarcas.getColumnModel().getColumn(0).setPreferredWidth(0);

        //Centrando el formulario
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }
    
    private String[] getColums(){
        String[] columnas = new String[]{"Id","Marca", "Pais"};
        return columnas;
    }
    
    private void getRows(){
        ResultSet rs = marDao.getListMarca();
        
        try{
            Object datos[] = new Object[3];
            
            while(rs.next()){
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = rs.getObject(i+1);
                }        
                modeloMarcas.addRow(datos);
            }
            
            rs.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al cargar datos." );
            Logger.getLogger(Marcas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Limpiar(){
        jtfMarcas.setText("");
        jcbxPais.setSelectedIndex(0);
        
        for (int i = 0; i < jtblMarcas.getRowCount(); i++) {
            modeloMarcas.removeRow(i);
            i-=1;
        }
    }
    
    //metodo para verificar los permisos para el formulario cargos
    private void accionRol(){
        Roles_DAO rolDao = new Roles_DAO();
        ResultSet rs = rolDao.listaTareas();
        int acciones;
        
        try {
            while(rs.next()){
                acciones = rs.getInt(1);
                switch(acciones){
                    case 19:
                        jrbtnAdd.setEnabled(true);
                        break;
                        
                    case 20:
                        jrbtnUpdate.setEnabled(true);
                        break;
                        
                    case 21:
                        jrbtnDelete.setEnabled(true);
                        break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Marcas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtgAcciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbtnAdd = new javax.swing.JRadioButton();
        jrbtnUpdate = new javax.swing.JRadioButton();
        jrbtnDelete = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblMarcas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfMarcas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbxPais = new javax.swing.JComboBox<>();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Acciones");

        jbtgAcciones.add(jrbtnAdd);
        jrbtnAdd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnAdd.setText("Agregar");
        jrbtnAdd.setEnabled(false);

        jbtgAcciones.add(jrbtnUpdate);
        jrbtnUpdate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnUpdate.setText("Editar");
        jrbtnUpdate.setEnabled(false);

        jbtgAcciones.add(jrbtnDelete);
        jrbtnDelete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnDelete.setText("Eliminar");
        jrbtnDelete.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtnUpdate)
                    .addComponent(jrbtnDelete)
                    .addComponent(jLabel1)
                    .addComponent(jrbtnAdd))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jrbtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jrbtnUpdate)
                .addGap(18, 18, 18)
                .addComponent(jrbtnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblMarcas.setModel(modeloMarcas);
        jtblMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblMarcas);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Marca");

        jtfMarcas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Pais");

        jcbxPais.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jcbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alemania", "China", "Corea del Sur", "España", "Estados Unidos", "Francia", "Inglaterra", "Japon", "Italia", "Servia" }));

        jbtnAceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnAceptar)
                                .addGap(30, 30, 30)
                                .addComponent(jbtnCancelar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfMarcas)
                                .addComponent(jcbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAceptar)
                    .addComponent(jbtnCancelar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        if(!jtfMarcas.getText().isEmpty() && jcbxPais.getSelectedIndex() >= 0){
            if(jrbtnAdd.isSelected()){
                int i;
                i = marDao.addMarca(jtfMarcas.getText(), jcbxPais.getSelectedItem().toString());
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se puede ingresar la marca");
                }
            } else if(jrbtnUpdate.isSelected()){
                int i;
                i = marDao.updateMarcas(jtfMarcas.getText(), jcbxPais.getSelectedItem().toString(), idMarca);
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se puede actualizar la marca");
                }
            } else if(jrbtnDelete.isSelected()){
                int i;
                i = marDao.deleteMarca(idMarca);
                
                if(i > 0){
                    Limpiar();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se pudo elimiar la marca");
                }
            }
        } else{
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
        }
        
        idMarca = -1;
        marDao.close();
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jtblMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMarcasMouseClicked
        if(jrbtnDelete.isSelected() || jrbtnUpdate.isSelected()){
            idMarca = (int) modeloMarcas.getValueAt(jtblMarcas.getSelectedRow(), 0);
            jtfMarcas.setText((String) modeloMarcas.getValueAt(jtblMarcas.getSelectedRow(), 1));
            String pa = (String) modeloMarcas.getValueAt(jtblMarcas.getSelectedRow(), 2);
            
            for (int i = 0; i < jcbxPais.getItemCount(); i++) {
                jcbxPais.setSelectedIndex(i);
                
                if(jcbxPais.getSelectedItem().toString().equals(pa)){
                    break;
                }
            }
        }
    }//GEN-LAST:event_jtblMarcasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jbtgAcciones;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox<String> jcbxPais;
    private javax.swing.JRadioButton jrbtnAdd;
    private javax.swing.JRadioButton jrbtnDelete;
    private javax.swing.JRadioButton jrbtnUpdate;
    private javax.swing.JTable jtblMarcas;
    private javax.swing.JTextField jtfMarcas;
    // End of variables declaration//GEN-END:variables
}
