/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Inventario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import local.DAO.Proveedores_DAO;
import local.DAO.Roles_DAO;
import local.PrincipalFrame.Principal_Frame;

/**
 *
 * @author Leonel
 */
public class Proveedores extends javax.swing.JInternalFrame {

    //Variables Globales
    DefaultTableModel ModeloProveedor;
    Proveedores_DAO probDao = new Proveedores_DAO();
    int idProveedor = -1;

    public Proveedores() {
        //Cargando los datos de la tabla
        ModeloProveedor = new DefaultTableModel(null, getColums());
        getRows();

        //Iniciando los componentes del formulario
        initComponents();
        setVisible(true);
        
        //Cargando acciones por rol
        accionRol();

        //Ocultar columnas
        jtblProveedor.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblProveedor.getColumnModel().getColumn(0).setMinWidth(0);
        jtblProveedor.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        //Centrando el formulario
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }

    private String[] getColums() {
        String[] colums = new String[]{"Id", "Proveedor", "Direccion", "PBX"};

        return colums;
    }

    private void getRows() {
        ResultSet rs = probDao.getListProveedor();   //obteniendo los dados mediante una clase DAO
        try {
            Object[] myObject = new Object[4];

            while (rs.next()) {
                for (int i = 0; i < myObject.length; i++) {
                    myObject[i] = rs.getObject(i + 1);
                }
                ModeloProveedor.addRow(myObject);
            }

            rs.close();
            probDao.close();
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpieza() {
        jtfDireccion.setText("");
        jtfPbx.setText("");
        jtfProveedor.setText("");

        for (int i = 0; i < jtblProveedor.getRowCount(); i++) {
            ModeloProveedor.removeRow(i);
            i -= 1;
        }
    }
    
    //metodo para verificar los permisos para el formulario cargos
    private void accionRol(){
        Roles_DAO rolDao = new Roles_DAO();
        ResultSet rs = rolDao.listaTareas();
        int acciones;
        
        try {
            while(rs.next()){
                acciones = rs.getInt(1);
                switch(acciones){
                    case 13:
                        jrbtnAgregar.setEnabled(true);
                        break;
                        
                    case 14:
                        jrbtnEditar.setEnabled(true);
                        break;
                        
                    case 15:
                        jrbtnEliminar.setEnabled(true);
                        break;
                }
                
                if(acciones > 15)
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgAcciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbtnAgregar = new javax.swing.JRadioButton();
        jrbtnEditar = new javax.swing.JRadioButton();
        jrbtnEliminar = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtfBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProveedor = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfProveedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfDireccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jtfPbx = new javax.swing.JTextField();
        jbtnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Acciones");

        btgAcciones.add(jrbtnAgregar);
        jrbtnAgregar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnAgregar.setText("Agregar");
        jrbtnAgregar.setEnabled(false);

        btgAcciones.add(jrbtnEditar);
        jrbtnEditar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnEditar.setText("Editar");
        jrbtnEditar.setEnabled(false);

        btgAcciones.add(jrbtnEliminar);
        jrbtnEliminar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbtnEliminar.setText("Eliminar");
        jrbtnEliminar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbtnEliminar)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbtnEditar)
                        .addComponent(jrbtnAgregar)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jrbtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jrbtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jrbtnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        jtfBuscar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtblProveedor.setModel(ModeloProveedor);
        jtblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProveedor);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Proveedor");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");

        jtfProveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfDireccion.setColumns(20);
        jtfDireccion.setRows(5);
        jScrollPane2.setViewportView(jtfDireccion);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("PBX");

        jtfPbx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jbtnAceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfProveedor)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jtfPbx)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jbtnAceptar)
                                .addGap(48, 48, 48)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAceptar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        if (!jtfDireccion.getText().isEmpty() && !jtfPbx.getText().isEmpty() && !jtfProveedor.getText().isEmpty()) {
            if (jrbtnAgregar.isSelected()) {
                int i;
                i = probDao.addProveedor(jtfProveedor.getText(), jtfDireccion.getText(), jtfPbx.getText());

                if (i > 0) {
                    limpieza();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se ha podido ingresar el proveedor");
                }
            } else if(jrbtnEditar.isSelected()){
                int i;
                i = probDao.updateProveedor(jtfProveedor.getText(), jtfPbx.getText(), jtfDireccion.getText(), idProveedor);
                if (i > 0) {
                    limpieza();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se ha podido actualizar el proveedor");
                }
                idProveedor = -1;
            } else if(jrbtnEliminar.isSelected()){
                int i;
                i = probDao.deleteProveedor(idProveedor);
                if (i > 0) {
                    limpieza();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se ha podido eliminar el proveedor");
                }
                
                idProveedor = -1;
            } else
                JOptionPane.showMessageDialog(null, "Debes de seleccionar una accion para realizar");
        } else {
            JOptionPane.showMessageDialog(null, "No puedes dejar campos en blanco");
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jtblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProveedorMouseClicked
        if (jrbtnEditar.isSelected() || jrbtnEliminar.isSelected()) {
            idProveedor = (int) ModeloProveedor.getValueAt(jtblProveedor.getSelectedRow(), 0);
            jtfProveedor.setText((String) ModeloProveedor.getValueAt(jtblProveedor.getSelectedRow(), 1));
            jtfDireccion.setText((String) ModeloProveedor.getValueAt(jtblProveedor.getSelectedRow(), 2));
            jtfPbx.setText((String) ModeloProveedor.getValueAt(jtblProveedor.getSelectedRow(), 3));
        }
    }//GEN-LAST:event_jtblProveedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAcciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JRadioButton jrbtnAgregar;
    private javax.swing.JRadioButton jrbtnEditar;
    private javax.swing.JRadioButton jrbtnEliminar;
    private javax.swing.JTable jtblProveedor;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextArea jtfDireccion;
    private javax.swing.JTextField jtfPbx;
    private javax.swing.JTextField jtfProveedor;
    // End of variables declaration//GEN-END:variables
}
