/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Ventas;

import local.PrincipalFrame.Principal_Frame;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import local.DAO.Repuestos_DAO;
import local.LC.Repuestos;

/**
 *
 * @author sanch
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        fillData();
        setVisible(true);
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }

    public static double round(double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(places, RoundingMode.HALF_UP);
        return bd.doubleValue();
    }

    private void fillData() {
        try {
            Repuestos_DAO repDao = new Repuestos_DAO();
            ResultSet repuestos = repDao.getRepuestos();
            while (repuestos.next()) {
                if (repuestos.getInt("respuestoIsActive") == 1) {
                    jCmbProducto.addItem(new Repuestos(repuestos.getInt("idrepuesto"), repuestos.getString("namerepuesto")));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void removeSelectedRows(JTable table){
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int[] rows = table.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            model.removeRow(rows[i]-i);
        }
    }
    
    private void actualizarTotal()
    {
        DefaultTableModel model = (DefaultTableModel) jTableListado.getModel();
        int cantidad;
        double dTotal = 0, precioUnitario;
        for (int x = 0; x < jTableListado.getRowCount(); x++)
        {
            cantidad = (int)model.getValueAt(x, 1);
            precioUnitario = (double)model.getValueAt(x, 2);
            model.setValueAt(round(cantidad*precioUnitario, 2), x, 3);
            dTotal += (double)model.getValueAt(x, 3);
        }
        jLblTotal.setText("$" + round(dTotal,2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCmbProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLblPrecioUnitario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLblSubTotal = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListado = new javax.swing.JTable();
        jSliderCantidad = new javax.swing.JSlider();
        jLblSliderCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblTotal = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venta");
        setMinimumSize(new java.awt.Dimension(390, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        jTxtCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtCliente.setForeground(java.awt.Color.gray);
        jTxtCliente.setText("Nombre cliente");
        jTxtCliente.setToolTipText("");
        jTxtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtClienteFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Producto:");

        jCmbProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbProductoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Precio Unitario:");

        jLblPrecioUnitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblPrecioUnitario.setText("$0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sub Total:");

        jLblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblSubTotal.setText("$0.00");

        jBtnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jTableListado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListado);

        jSliderCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderCantidadStateChanged(evt);
            }
        });

        jLblSliderCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblSliderCount.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total:");

        jLblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblTotal.setText("$0.00");
        jLblTotal.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPrecioUnitario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblSubTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblSliderCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLblSliderCount))
                    .addComponent(jSliderCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLblPrecioUnitario)
                    .addComponent(jLabel5)
                    .addComponent(jLblSubTotal)
                    .addComponent(jBtnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLblTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtClienteFocusGained
        // TODO add your handling code here:
        if (jTxtCliente.getText().equals("Nombre cliente")) {
            jTxtCliente.setForeground(Color.BLACK);
            jTxtCliente.setText("");
        }
    }//GEN-LAST:event_jTxtClienteFocusGained

    private void jTxtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtClienteFocusLost
        // TODO add your handling code here:
        if (jTxtCliente.getText().isEmpty()) {
            jTxtCliente.setForeground(Color.GRAY);
            jTxtCliente.setText("Nombre cliente");
        }
    }//GEN-LAST:event_jTxtClienteFocusLost

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableListado.getModel();
        Double dSubTotal = Double.parseDouble(jLblSubTotal.getText().replace("$", ""));
        Repuestos item = (Repuestos) jCmbProducto.getSelectedItem();
        model.addRow(new Object[]{
            item.getDescription(),
            jSliderCantidad.getValue(),
            round(Double.parseDouble(jLblPrecioUnitario.getText().replace("$", "")), 2),
            round(dSubTotal, 2)
        });
        Double dTotal = Double.parseDouble(jLblTotal.getText().replace("$", ""));
        dTotal += dSubTotal;
        jLblTotal.setText("$" + round(dTotal,2));
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jCmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbProductoActionPerformed
        // TODO add your handling code here:
        try {
            Repuestos item = (Repuestos) jCmbProducto.getSelectedItem();
            Repuestos_DAO repDao = new Repuestos_DAO();
            ResultSet rs = repDao.getRepuestos(item.getId());
            if (rs.next()) {
                jLblPrecioUnitario.setText("$" + rs.getDouble("precioventa"));
                jLblSubTotal.setText("$" + rs.getDouble("precioventa"));
                if (rs.getInt("cantidad") > 0) {
                    jSliderCantidad.setMinimum(1);
                    jSliderCantidad.setMaximum(rs.getInt("cantidad"));
                    jSliderCantidad.setValue(1);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCmbProductoActionPerformed

    private void jSliderCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderCantidadStateChanged
        // TODO add your handling code here:
        jLblSliderCount.setText(String.valueOf(jSliderCantidad.getValue()));
        Double dPrecioUnitario = Double.parseDouble(jLblPrecioUnitario.getText().replace("$", ""));
        Double dSubTotal = dPrecioUnitario * jSliderCantidad.getValue();
        jLblSubTotal.setText("$" + round(dSubTotal, 2));
    }//GEN-LAST:event_jSliderCantidadStateChanged

    private void jTableListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 127)
        {
            removeSelectedRows(this.jTableListado);
            actualizarTotal();
        }
    }//GEN-LAST:event_jTableListadoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JComboBox<Repuestos> jCmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblPrecioUnitario;
    private javax.swing.JLabel jLblSliderCount;
    private javax.swing.JLabel jLblSubTotal;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderCantidad;
    private javax.swing.JTable jTableListado;
    private javax.swing.JTextField jTxtCliente;
    // End of variables declaration//GEN-END:variables
}
