/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Empleados;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import local.DAO.Cargos_DAO;
import local.DAO.Roles_DAO;
import local.PrincipalFrame.Principal_Frame;

/**
 *
 * @author Leonel
 */
public class Cargos extends javax.swing.JInternalFrame {

    //Variables Globales
    DefaultTableModel cargosView;
    Cargos_DAO carDao = new Cargos_DAO();
    int idCargo = -1;

    public Cargos() {
        //Cargonado la tabla de datos
        cargosView = new DefaultTableModel(null, getColums());
        setRows();

        //Inizializando el formulario
        initComponents();
        setVisible(true);
        
        //Cargando las accions permitidas
        accionRol();

        //Ocultando la primera columna
        jtblViewCargos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblViewCargos.getColumnModel().getColumn(0).setMinWidth(0);
        jtblViewCargos.getColumnModel().getColumn(0).setPreferredWidth(0);

        //Centrando el formulario
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }

    //seteando la cabecera de la tabla
    private String[] getColums() {
        String[] colums = new String[]{"Id", "Cargo", "Salario", "Descripcion"};

        return colums;
    }

    //metodo para llenar la tabla 
    private void setRows() {
        ResultSet rs = carDao.getRowsCargo();   //obteniendo los dados mediante una clase DAO
        try {
            Object[] myObject = new Object[4];

            while (rs.next()) {
                for (int i = 0; i < myObject.length; i++) {
                    myObject[i] = rs.getObject(i + 1);
                }
                cargosView.addRow(myObject);
            }

            rs.close();
            carDao.close();
        } catch (SQLException ex) {
            Logger.getLogger(Cargos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //Metodo para limpiar el formulario
    public void limpieza() {
        jtaDescripcion.setText("");
        jtfCargo.setText("");
        jtfSalario.setText("");

        for (int i = 0; i < jtblViewCargos.getRowCount(); i++) {
            cargosView.removeRow(i);
            i -= 1;
        }
    }
    
    //metodo para verificar los permisos para el formulario cargos
    private void accionRol(){
        Roles_DAO rolDao = new Roles_DAO();
        ResultSet rs = rolDao.listaTareas();
        int acciones;
        
        try {
            while(rs.next()){
                acciones = rs.getInt(1);
                switch(acciones){
                    case 1:
                        jrbAdd.setEnabled(true);
                        break;
                        
                    case 2:
                        jrbEdit.setEnabled(true);
                        break;
                        
                    case 3:
                        jrbDelete.setEnabled(true);
                        break;
                }
                
                if(acciones > 3)
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cargos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpAcciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbAdd = new javax.swing.JRadioButton();
        jrbEdit = new javax.swing.JRadioButton();
        jrbDelete = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtfBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblViewCargos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCargo = new javax.swing.JTextField();
        jtfSalario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("ACCIONES");

        bgpAcciones.add(jrbAdd);
        jrbAdd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbAdd.setText("Agregar");
        jrbAdd.setEnabled(false);

        bgpAcciones.add(jrbEdit);
        jrbEdit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbEdit.setText("Editar");
        jrbEdit.setEnabled(false);

        bgpAcciones.add(jrbDelete);
        jrbDelete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbDelete.setText("Eliminar");
        jrbDelete.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbEdit)
                    .addComponent(jrbAdd)
                    .addComponent(jrbDelete)
                    .addComponent(jLabel1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jrbAdd)
                .addGap(18, 18, 18)
                .addComponent(jrbEdit)
                .addGap(18, 18, 18)
                .addComponent(jrbDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        jtfBusqueda.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfBusquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBusquedaKeyTyped(evt);
            }
        });

        jtblViewCargos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtblViewCargos.setModel(cargosView);
        jtblViewCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblViewCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblViewCargos);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Cargo:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Salario:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion:");

        jtfCargo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfSalario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSalarioKeyTyped(evt);
            }
        });

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(jtaDescripcion);

        jbtnAceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jtfSalario)
                            .addComponent(jtfCargo))
                        .addGap(90, 90, 90)
                        .addComponent(jbtnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAceptar)
                    .addComponent(jbtnCancelar))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        if (jrbAdd.isSelected()) {

            int isAdd;

            if (!jtfCargo.getText().isEmpty() && !jtfSalario.getText().isEmpty() && !jtaDescripcion.getText().isEmpty()) {
                isAdd = carDao.addCargo(jtfCargo.getText(), Double.parseDouble(jtfSalario.getText()), jtaDescripcion.getText());

                if (isAdd > 0) {
                    limpieza();
                    setRows();
                } else {
                    JOptionPane.showMessageDialog(null, "Lo senitmos no se pudieron ingresar los datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No pueden existir campos en blanco, por favor completalos todos");
            }
        } else if (jrbEdit.isSelected()) {
            int isUpdate;

            if (!jtfCargo.getText().isEmpty() && !jtfSalario.getText().isEmpty() && !jtaDescripcion.getText().isEmpty()) {
                if (idCargo > 0) {
                    isUpdate = carDao.updateCargo(idCargo, jtfCargo.getText(), Double.parseDouble(jtfSalario.getText()), jtaDescripcion.getText());

                    if (isUpdate > 0) {
                        limpieza();
                        setRows();
                        idCargo = -1;
                    } else {
                        JOptionPane.showMessageDialog(null, "Lo senitmos no se pudieron ingresar los datos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de elegin un campo de la tabla para realizar la accion");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No pueden existir campos en blanco, por favor completalos todos");
            }
        } else if (jrbDelete.isSelected()) {
            int isDelete;

            if (idCargo > 0) {
                isDelete = carDao.deleteCargos(idCargo);

                if (isDelete > 0) {
                    limpieza();
                    setRows();
                    idCargo = -1;
                } else {
                    JOptionPane.showMessageDialog(null, "Lo senitmos no se pudieron ingresar los datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes de elegin un campo de la tabla para realizar la accion");
            }

        }
        carDao.close();
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jtfSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSalarioKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && jtfSalario.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSalarioKeyTyped

    private void jtblViewCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblViewCargosMouseClicked
        if (jrbDelete.isSelected() || jrbEdit.isSelected()) {
            //Cargando los datos a los jTextFiel
            jtfCargo.setText((String) cargosView.getValueAt(jtblViewCargos.getSelectedRow(), 1));

            jtaDescripcion.setText((String) cargosView.getValueAt(jtblViewCargos.getSelectedRow(), 3));

            //Ingresando el id
            idCargo = (int) cargosView.getValueAt(jtblViewCargos.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_jtblViewCargosMouseClicked

    private void jtfBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBusquedaKeyTyped
        
    }//GEN-LAST:event_jtfBusquedaKeyTyped

    private void jtfBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBusquedaKeyPressed
        String search = jtfBusqueda.getText();

        if (search.isEmpty()) {
            limpieza();
            setRows();
        } else {
            limpieza();
            ResultSet rs = carDao.getSearchRows(search);   //obteniendo los dados mediante una clase DAO
            try {
                Object[] myObject = new Object[4];

                while (rs.next()) {
                    for (int i = 0; i < myObject.length; i++) {
                        myObject[i] = rs.getObject(i + 1);
                    }
                    cargosView.addRow(myObject);
                }

                rs.close();
                carDao.close();
            } catch (SQLException ex) {
                Logger.getLogger(Cargos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtfBusquedaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpAcciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JRadioButton jrbAdd;
    private javax.swing.JRadioButton jrbDelete;
    private javax.swing.JRadioButton jrbEdit;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTable jtblViewCargos;
    private javax.swing.JTextField jtfBusqueda;
    private javax.swing.JTextField jtfCargo;
    private javax.swing.JTextField jtfSalario;
    // End of variables declaration//GEN-END:variables
}
