/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.Usuarios;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import local.DAO.Empleados_DAO;
import local.DAO.Roles_DAO;
import local.DAO.Usuarios_DAO;
import local.PrincipalFrame.Principal_Frame;
import local.Security.EncriptadorPassword;

/**
 *
 * @author Leonel
 */
public class Usuarios extends javax.swing.JInternalFrame {

    //Variables globales
    int idUsuario = -1;
    DefaultTableModel viewUser;
    Usuarios_DAO userDao = new Usuarios_DAO();
    Empleados_DAO empDao = new Empleados_DAO();
    Roles_DAO rolDao = new Roles_DAO();
    
    public Usuarios() {
        //Cragando el modelo de la tabla
        viewUser = new DefaultTableModel(null, getColums());
        getRows();
        
        //Iniciando los componentes del formulario
        initComponents();
        setVisible(true);
        
        //Cargando las accioes por rol
        accionRol();
        
        //Cargando los comboBox
        empDao.listaEmpleados(jcbxEmpleado);
        rolDao.listaRoles(jcbxRol);
        
        //Ocultar columnas
        jtbUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        jtbUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        jtbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);

        //Centrando el formulario
        int wdith = Principal_Frame.jdpContenedor.getWidth() - this.getWidth();
        int hght = Principal_Frame.jdpContenedor.getHeight() - this.getHeight();
        this.setLocation(wdith / 2, hght / 2);
    }
    
    private String[] getColums() {
        String[] colums = new String[]{"Id", "Usuario", "Contraseña", "Empleado", "Rol"};

        return colums;
    }

    //Metodo para obtener las filas de la tabla
    private void getRows() {
        ResultSet rs = userDao.getListUser();   //obteniendo los dados mediante una clase DAO
        try {
            Object[] myObject = new Object[5];

            while (rs.next()) {
                for (int i = 0; i < myObject.length; i++) {
                    myObject[i] = rs.getObject(i + 1);
                }
                viewUser.addRow(myObject);
            }

            rs.close();
            userDao.close();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Devuelbe la contraseña ya sea encriptada o desencriptada
    private String passwdDevelop(String pwd, int ncrip){
        EncriptadorPassword encryp = new EncriptadorPassword("J@va3ncr1p73r");
        String pass = "";
        
        if(ncrip == 1){ //para encriptar
            pass = encryp.encrypt(pwd);
        } else if(ncrip == 2){ //para desencriptar
            pass = encryp.decrypt(pwd);
        }
        
        return pass;
    }
    
    //metodo para verificar los permisos para el formulario cargos
    private void accionRol(){
        ResultSet rs = rolDao.listaTareas();
        int acciones;
        try {
            while(rs.next()){
                acciones = rs.getInt(1);
                switch(acciones){
                    case 10:
                        jrbAdd.setEnabled(true);
                        break;
                        
                    case 11:
                        jrbUpdate.setEnabled(true);
                        break;
                        
                    case 12:
                        jrbDelete.setEnabled(true);
                        break;
                }
                
                if(acciones > 12)
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void limpieza(){
        jtfUsuario.setText("");
        jtfPass1.setText("");
        jtfPass2.setText("");
        jcbxEmpleado.setSelectedIndex(0);
        jcbxRol.setSelectedIndex(0);
        
        for (int i = 0; i < jtbUsuarios.getRowCount(); i++) {
            viewUser.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtgAcciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbAdd = new javax.swing.JRadioButton();
        jrbUpdate = new javax.swing.JRadioButton();
        jrbDelete = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();
        jtfBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jtfPass2 = new javax.swing.JPasswordField();
        jtfPass1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jcbxEmpleado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbxRol = new javax.swing.JComboBox<>();
        jbtnAceptar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Acciones");

        jbtgAcciones.add(jrbAdd);
        jrbAdd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbAdd.setText("Agregar");
        jrbAdd.setEnabled(false);

        jbtgAcciones.add(jrbUpdate);
        jrbUpdate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbUpdate.setText("Editar");
        jrbUpdate.setEnabled(false);

        jbtgAcciones.add(jrbDelete);
        jrbDelete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrbDelete.setText("Eliminar");
        jrbDelete.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbAdd)
                    .addComponent(jrbUpdate)
                    .addComponent(jrbDelete)
                    .addComponent(jLabel1))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jrbAdd)
                .addGap(18, 18, 18)
                .addComponent(jrbUpdate)
                .addGap(18, 18, 18)
                .addComponent(jrbDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        jtbUsuarios.setModel(viewUser);
        jtbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUsuarios);

        jtfBuscar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");

        jtfUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfPass2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfPass1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Empleado");

        jcbxEmpleado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Rol");

        jcbxRol.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jbtnAceptar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(jtfPass1)
                                            .addComponent(jtfUsuario)))
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnCancelar)
                                        .addGap(73, 73, 73))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jcbxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAceptar)
                            .addComponent(jbtnCancelar))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        if(!jtfUsuario.getText().isEmpty() && jtfPass1.getPassword().length > 0 && jtfPass2.getPassword().length > 0 && jcbxEmpleado.getSelectedIndex() > 0 && jcbxRol.getSelectedIndex() > 0){
            if(jrbAdd.isSelected()){
                int nameAprove = userDao.userExist(jtfUsuario.getText());
                String pass1 = String.valueOf(jtfPass1.getPassword());
                String pass2 = String.valueOf(jtfPass2.getPassword());
                
                if(nameAprove == 0 && pass1.equals(pass2)){
                    pass2 = passwdDevelop(pass1, 1);
                    local.LC.Roles r = (local.LC.Roles) jcbxRol.getSelectedItem();
                    local.LC.Empleados e = (local.LC.Empleados) jcbxEmpleado.getSelectedItem();
                    
                    int rol = r.getId();
                    int emp = e.getIdempleado();
                    
                    int i = userDao.addUser(jtfUsuario.getText(), pass2, emp, rol);
                    
                    if(i > 0){
                        limpieza();
                        getRows();
                    }
                    else
                        JOptionPane.showMessageDialog(null, "No se pudo ingresar el usuario");
                } else if(!pass1.equals(pass2)){
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                } else if(nameAprove == 1){
                    JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe");
                }
                
                idUsuario = -1;
            } else if(jrbUpdate.isSelected()){
                int nameAprove = userDao.userExist(jtfUsuario.getText());
                String pass1 = String.valueOf(jtfPass1.getPassword());
                String pass2 = String.valueOf(jtfPass2.getPassword());
                
                if(nameAprove == 0 && pass1.equals(pass2)){
                    pass2 = passwdDevelop(pass1, 1);
                    local.LC.Roles r = (local.LC.Roles) jcbxRol.getSelectedItem();
                    local.LC.Empleados e = (local.LC.Empleados) jcbxEmpleado.getSelectedItem();
                    
                    int rol = r.getId();
                    int emp = e.getIdempleado();
                    
                    int i = userDao.updateUser(idUsuario, jtfUsuario.getText(), pass2, emp, rol);
                    
                    if(i > 0){
                        limpieza();
                        getRows();
                    }
                    else
                        JOptionPane.showMessageDialog(null, "No se pudo actualizar el usuario");
                } else if(!pass1.equals(pass2)){
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                } else if(nameAprove == 1){
                    JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe");
                }
                
                idUsuario = -1;
            } else if(jrbDelete.isSelected()){
                int i = userDao.deleteUser(idUsuario);
                
                if(i > 0){
                    limpieza();
                    getRows();
                } else{
                    JOptionPane.showMessageDialog(null, "No se puede eliminar el usuario");
                }
                
                idUsuario = -1;
            }
        } else{
            JOptionPane.showMessageDialog(null, "no dejes campos vacios por favor");
        }
        
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jtbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUsuariosMouseClicked
        if(jrbDelete.isSelected() || jrbUpdate.isSelected()){
            idUsuario = (int) viewUser.getValueAt(jtbUsuarios.getSelectedRow(), 0);
            jtfUsuario.setText((String) viewUser.getValueAt(jtbUsuarios.getSelectedRow(), 1));
            String passEncrip = (String) viewUser.getValueAt(jtbUsuarios.getSelectedRow(), 2);
            
            jtfPass1.setText(passwdDevelop(passEncrip, 2));
            jtfPass2.setText(passwdDevelop(passEncrip, 2));
            
            String rol = (String) viewUser.getValueAt(jtbUsuarios.getSelectedRow(), 4);
            String emp = (String) viewUser.getValueAt(jtbUsuarios.getSelectedRow(), 3);
            
            for (int i = 0; i < jcbxRol.getItemCount(); i++) {
                jcbxRol.setSelectedIndex(i);
                if(rol.equals(jcbxRol.getSelectedItem().toString()))
                    break;
            }
            
            for (int i = 0; i < jcbxEmpleado.getItemCount(); i++) {
                jcbxEmpleado.setSelectedIndex(i);
                if(emp.equals(jcbxEmpleado.getSelectedItem().toString()))
                    break;
            }
        }
    }//GEN-LAST:event_jtbUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jbtgAcciones;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JComboBox<String> jcbxEmpleado;
    private javax.swing.JComboBox<String> jcbxRol;
    private javax.swing.JRadioButton jrbAdd;
    private javax.swing.JRadioButton jrbDelete;
    private javax.swing.JRadioButton jrbUpdate;
    private javax.swing.JTable jtbUsuarios;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JPasswordField jtfPass1;
    private javax.swing.JPasswordField jtfPass2;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
